### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/infografia-Nancy2050-1#2]
![INFOGRAFIA V2](https://user-images.githubusercontent.com/64548201/132168079-ff28652e-1bb3-4081-abc2-d86db353f781.png)
[INFOGRAFIA V2.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Nancy2050-1/files/7113683/INFOGRAFIA.V2.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20 %
Calificó: Antonio González Hernández

Contiene toda la información y está bien organizada

**Comment by josealfredo79** [comment]
Bien hecho y revisado
